In [1]:
import numpy as np

In [2]:
nn_0 = 2
nn_1 = 2
nn_2 = 2

# Sesgos y pesos
b1 = np.array([[0.45], [0.35]])
W1 = np.array([[0.15, 0.20], [0.25, 0.30]])
b2 = np.array([[0.30], [0.45]])
W2 = np.array([[0.35, 0.48], [0.40, 0.45]])

# Vectores de entrada y salida
Z1 = np.zeros((nn_1,1))
A1 = np.zeros((nn_1,1))
Z2 = np.zeros((nn_2,1))
A2 = np.zeros((nn_2,1))

In [3]:
# Función de propagación hacia adelante
def propaga(Xo):
    Z1 = np.dot(W1,Xo) + b1
    A1 = sig(Z1)
    Z2 = np.dot(W2,A1) + b2
    A2 = sig(Z2)
    return A2, Z2, A1, Z1

# Función de activación de sigmoide
def sig(s):
    return 1/(1+np.exp(-s))

def dSig(s):
    df = sig(s.T[0])*(sig(s.T[0]))
    ds = np.diag(df)
    return ds

In [4]:
X = np.array([[0.05], [0.10]])
Yr = np.array([[0.01], [0.99]])

In [5]:
A2, Z2, A1, Z1 = propaga(X)
print(A2)

[[0.69051105]
 [0.72421384]]


In [6]:
def error(A2, Yd):
    err = Yd - A2
    return err

In [7]:
def backpropagation(X, Yr, A2, Z2, A1, Z1):
    delta2 = np.dot(dSig(Z2), error(A2, Yr))
    dEdW2 = -np.dot(delta2, A1.T) # Corrección para W2
    dEdb2 = -delta2

    delta1 = np.dot(np.dot(dSig(Z1), W2.T), delta2)
    dEdW1 = -np.dot(delta1,X.T) # Correccion para W1

    dEdb1 = -delta1
    return dEdW2, dEdb2, dEdW1, dEdb1

In [8]:
dEdW2, dEdb2, dEdW1, dEdb1 = backpropagation(X, Yr, A2, Z2, A1, Z1)

In [9]:
eta = 0.1

In [10]:
W2 = W2 - eta * dEdW2
b2 = b2 - eta * dEdb2
W1 = W1 - eta * dEdW1
b1 = b1 - eta * dEdb1

In [11]:
A2, Z2, A1, Z1 = propaga(X)
print(A2)

[[0.67821878]
 [0.72890846]]


In [12]:
i = 0
while i < 50000:
    A2, Z2, A1, Z1 = propaga(X)
    err = error(A2, Yr)

    dEdW2, dEdb2, dEdW1, dEdb1 = backpropagation(X, Yr, A2, Z2, A1, Z1)
    W2 = W2 - eta * dEdW2
    b2 = b2 - eta * dEdb2
    W1 = W1 - eta * dEdW1
    b1 = b1 - eta * dEdb1

    i = i + 1
print(A2)

[[0.03341429]
 [0.9900029 ]]
